### ISSUE TITLE
Unresponsive toolbar

### ISSUE THREAD

**Issue by david-3** [sboulema/TSVN#24]
I've downloaded and installed TSVN without any problem. The toolbar is available in VS and looks great. At no time, however, am I able to get any of the toolbar buttons to do anything. There are no errors; just nothing happens. Can you help?

Note that I read through the instructions and have added the Tortoise bin path in my environment path list. I also have TortoiseSVN 1.9 installed and working fine (and have enjoyed it for several months). Also, I'm running VS2017 Community Edition and have an older VS2015 on the same machine.

UPDATE: I've noticed that the tsvn right-click features work inside of solution explorer. However, the typical icons (green checkmarks, orange squares, etc.) next to each file still isn't showing. Also the toolbar items/buttons as well as the first layer of menu items in the tsvn main menu are still unresponsive.

**Comment by sboulema** [comment]
Did you install TortoiseSVN with the client tools? https://i.stack.imgur.com/31I6E.jpg

**Comment by david-3** [comment]
I'm pretty sure I just installed it with default settings.

**Comment by sboulema** [comment]
A reinstall/modify of TortoiseSVN should fix it. 
Regarding your update: status icons is still on the todo list: #16

**Comment by david-3** [comment]
The reinstall/modify didn't seem to do anything. The toolbar and first-layer of the Tsvn main menu still do nothing. However, as before, the choices in the second-layer of the main menu (ie. Tsvn -> Tsvn -> Blame, etc.) work fine. There are fewer features in that list (ie. no patching, branching, or switching) but those still work as expected.

**Comment by david-3** [comment]
Oh...and I did perform the reboot after reinstalling.

**Comment by david-3** [comment]
sboulema,
I had VisualSVN on my machine before installing Tsvn. I didn't want to take any chances of it causing conflicts with Tsvn, so I removed it before beginning the installation. Can't see how that could be contributing to the current issue but I thought I'd mention it, just in case.

**Comment by sboulema** [comment]
What is the output from 'svn info' when run in a CMD prompt inside your repo folder?

**Comment by david-3** [comment]
I opened a cmd prompt and pointed it to the '.svn' folder of a project I've got open in visual studio. From the '.svn' folder I typed 'svn info' (minus the quotes of course) and it responded: 
> "'svn' is not recognized as an internal or external command, operable program or batch file.

**Comment by sboulema** [comment]
Can you please try this debug build: https://github.com/sboulema/TSVN/releases/tag/v3.8-beta.1
Reproduce the problem and let me know the TSVN output in the VS 'Output' window.

Example output:
![Debug](http://i.imgur.com/8qIQU2t.png)

**Comment by generalistr6** [comment]
Thank you for useful TSVN add-in. I like to use this add-in.
Anyway now I have problem and found error message from TSVN debug output.
The message is as below.
- svn: E200009: Could not display info for all targets because some targets don't exist

The target is the folder including *.sln file. But my folder structure is not good for it. Is there anyway to change the target folder?

**Comment by Sacryn** [comment]
I'm having the same issue. Possible reason; my solution file is not located in the SVN tree. The cmake scripts creates the project files in an untracked folder. Running "svn info" in the solution folder gives the following output:

`svn: warning: W155010: The node 'E:\.........\CMAKE_BUILD_VS2015' was not found.
svn: E200009: Could not display info for all targets because some targets don't exist`

Is there any way to inform the plugin which folder is the root folder of the repo?

**Comment by sboulema** [comment]
I will look into the possibility of manually specifying the root folder, to be able to handle these situations.

**Comment by sboulema** [comment]
Please try the new 4.1 release.

Go to Tsvn -> Windows -> Options and set your repository root folder

**Comment by Sacryn** [comment]
Just installed and tried the 4.1 release. Setting the repo folder manually works like a charm! All TSVN menu options now work as supposed.

**Comment by sboulema** [comment]
Great to hear!
