### ISSUE TITLE
Error on start in VS2017

### ISSUE THREAD

**Issue by opus1269** [sboulema/TSVN#60]
If you close VS2017 with the "TSVN Pending Changes" window as the active window, the next time you start VS without loading a solution, you get a series of dialog popups as so:

![image](https://user-images.githubusercontent.com/10528250/65383254-62ca9100-dcd8-11e9-939d-e8ab692d8c4e.png)

You can just click OK on them and VS will them startup, but it is a pain.

**Comment by sboulema** [comment]
Thanks for reporting!

Should be fixed in the new release 🚀

**Comment by opus1269** [comment]
It is fixed. Thanks.

Not sure if this is the norm, but,I had to download the xxx.54 version from the gallery. It still has .53 in the marketplace link

**Comment by ionescudev** [comment]
> It is fixed. Thanks.
> 
> Not sure if this is the norm, but,I had to download the xxx.54 version from the gallery. It still has .53 in the marketplace link

What do you mean, post a link to the xxx.54 version taht you downloaded and fixed the issue ?

**Comment by ionescudev** [comment]
http://vsixgallery.com/extension/07fd7462-cd4b-433b-9ab5-8ad3ad87bc65/

I downloaded this, didnt fix anything.
